version: '3.4'

services:
  healthcheck:
    image: xabarilcoding/healthchecksui:5.0.0
    depends_on:
      - grabber
      - archiver
      - collector
      - compressor
      - yandestore

  redis-state:
    image: redis:7

  redis-pubsub:
    image: redis:7

  seq:
    image: datalust/seq:latest

  zipkin:
    image: openzipkin/zipkin-slim

  grabber:
    image: ${DOCKER_REGISTRY-}ashlakeservicesgrabber
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Grabber/Dockerfile
    depends_on:
      - grabber-redis

  grabber-dapr:
    image: "daprio/daprd:1.7.4"
    network_mode: "service:grabber"
    depends_on:
      - grabber

  grabber-redis:
    image: redis:7

  archiver:
    image: ${DOCKER_REGISTRY-}ashlakeservicesarchiver
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Archiver/Dockerfile
    depends_on:
      - archiver-mongo
      - archiver-redis

  archiver-dapr:
    image: "daprio/daprd:1.7.4"
    network_mode: "service:archiver"
    depends_on:
      - archiver

  archiver-mongo:
    image: mongo:4

  archiver-redis:
    image: redis:7

  collector:
    image: ${DOCKER_REGISTRY-}ashlakeservicescollector
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Collector/Dockerfile
    depends_on:
      - collector-minio
      - collector-redis

  collector-dapr:
    image: "daprio/daprd:1.7.4"
    network_mode: "service:collector"
    depends_on:
      - collector

  collector-minio:
    image: minio/minio:latest

  collector-redis:
    image: redis:7

  compressor:
    image: ${DOCKER_REGISTRY-}ashlakeservicescompressor
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Compressor/Dockerfile
    depends_on:
      - compressor-minio

  compressor-minio:
    image: minio/minio:latest

  compressor-dapr:
    image: "daprio/daprd:1.7.4"
    network_mode: "service:compressor"
    depends_on:
      - compressor

  compressor-redis:
    image: redis:7

  yandestore:
    image: ${DOCKER_REGISTRY-}ashlakeservicesyandestore
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.YandeStore/Dockerfile
    depends_on:
      - yandestore-redis
      - yandestore-postgres

  yandestore-dapr:
    image: "daprio/daprd:1.7.4"
    network_mode: "service:yandestore"
    depends_on:
      - yandestore

  yandestore-redis:
    image: redis:7

  yandestore-postgres:
    image: postgres:14