version: '3.4'

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - "27017:27017"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  redis-easycaching:

  redis-hangfire:

  rabbitmq:
    ports:
      - "5672:5672"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  zipkin:
    ports:
      - "9411:9411"

  healthcheck:
    environment:
      - HealthChecksUI__HealthChecks__0__Name=Grabber API
      - HealthChecksUI__HealthChecks__0__Uri=http://grabber/hc
      - HealthChecksUI__HealthChecks__1__Name=Archiver API
      - HealthChecksUI__HealthChecks__1__Uri=http://archiver/hc
      - HealthChecksUI__HealthChecks__2__Name=Collector API
      - HealthChecksUI__HealthChecks__2__Uri=http://collector/hc
      - HealthChecksUI__HealthChecks__3__Name=YandeStore API
      - HealthChecksUI__HealthChecks__3__Uri=http://yandestore/hc
    ports:
      - "5107:80"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  grabber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - YandeUrl=https://yande.re/
      - EasycachingRedisHost=redis-easycaching
      - SeqServerUrl=http://seq
    ports:
      - "80"

  grabber-dapr:
    command: ["./daprd",
      "-app-id", "grabber",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-max-request-size","50",
      "-log-level", "debug"
      ]
    volumes:
      - "./dapr/components/:/components"

  archiver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDatabaseConnectionString=mongodb://mongoadmin:mongoadmin@mongo:27017
      - HangfireConnectionString=redis-hangfire:6379
      - SeqServerUrl=http://seq
    ports:
      - "80"

  archiver-dapr:
    command: ["./daprd",
      "-app-id", "archiver",
      "-app-port", "80",
      "-components-path", "/components",
      "-log-level", "debug",
      "-placement-host-address", "dapr-placement:50000"
      ]
    volumes:
      - "./dapr/components/:/components"
     
  collector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ImageStorageEndpoint=minio:9000
      - ImageStorageAccessKey=minio
      - ImageStorageSecretKey=minio123
      - HangfireConnectionString=redis-hangfire:6379
      - SeqServerUrl=http://seq
    ports:
      - "80"

  collector-dapr:
    command: ["./daprd",
      "-app-id", "collector",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-max-request-size","200",
      "-log-level", "debug",
      "-placement-host-address", "dapr-placement:50000"
      ]
    volumes:
      - "./dapr/components/:/components"

  yandestore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DBConnectionString=Host=postgres;Database=postgres;Username=root;Password=postgres
      - RetryMigrations=true
      - SeqServerUrl=http://seq
    ports:
      - "80"

  yandestore-dapr:
    command: ["./daprd",
      "-app-id", "yandestore",
      "-app-port", "80",
      "-components-path", "/components",
      "-log-level", "debug",
      "-placement-host-address", "dapr-placement:50000"
      ]
    volumes:
      - "./dapr/components/:/components"
