version: '3.4'

services:
  healthcheck:
    image: xabarilcoding/healthchecksui:5.0.0
    depends_on:
      - archiver

  rabbitmq:
    image: rabbitmq:3-management-alpine

  seq:
    image: datalust/seq:latest

  booru-api:
    image: youliao/booruapi:220710

  archiver:
    image: ${DOCKER_REGISTRY-}ashlakeservicesarchiver
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Archiver/Dockerfile
    depends_on:
      - archiver-mongo
      - archiver-redis

  archiver-mongo:
    image: mongo:4

  archiver-redis:
    image: redis:7

  collector:
    image: youliao/collector:220712
    depends_on:
      - collector-aria2
      - collector-minio

  collector-minio:
    image: minio/minio:latest

  collector-imgproxy:
    image: darthsim/imgproxy:latest
    depends_on:
      - collector-minio

  collector-aria2:
    image: superng6/aria2:webui-latest
    depends_on:
      - collector-minio

  #yandestore:
  #  image: ${DOCKER_REGISTRY-}ashlakeservicesyandestore
  #  build:
  #    context: .
  #    dockerfile: src/Services/AshLake.Services.YandeStore/Dockerfile
  #  depends_on:
  #    - yandestore-redis
  #    - yandestore-postgres

  #yandestore-dapr:
  #  image: "daprio/daprd:1.7.4"
  #  network_mode: "service:yandestore"
  #  depends_on:
  #    - yandestore

  #yandestore-postgres:
  #  image: postgres:14

  #yandestore-redis:
  #  image: redis:7