version: '3.4'

services:
  healthcheck:
    environment:
      - HealthChecksUI__HealthChecks__0__Name=Grabber API
      - HealthChecksUI__HealthChecks__0__Uri=http://grabber/hc
      - HealthChecksUI__HealthChecks__1__Name=Archiver API
      - HealthChecksUI__HealthChecks__1__Uri=http://archiver/hc
      - HealthChecksUI__HealthChecks__2__Name=Collector API
      - HealthChecksUI__HealthChecks__2__Uri=http://collector/hc
      - HealthChecksUI__HealthChecks__3__Name=Compressor API
      - HealthChecksUI__HealthChecks__3__Uri=http://compressor/hc
      - HealthChecksUI__HealthChecks__4__Name=YandeStore API
      - HealthChecksUI__HealthChecks__4__Uri=http://yandestore/hc
    ports:
      - "5107:80"

  seq:
    environment:
      - ACCEPT_EULA=Y
      - SEQ_CACHE_SYSTEMRAMTARGET=0.2
    volumes:
      - seq-data:/data
    ports:
      - "5340:80"

  zipkin:
    ports:
      - "9411:9411"

  grabber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - YandeUrl=https://yande.re/
      - DanbooruUrl=https://danbooru.donmai.us/
      - KonachanUrl=https://konachan.com/
      - EasycachingRedisHost=grabber-redis
      - SeqServerUrl=http://seq
    ports:
      - "30001:80"

  grabber-dapr:
    command: ["./daprd",
      "-app-id", "grabber",
      "-app-port", "80",
      "-components-path", "/components",
      "-enable-profiling","true",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    deploy:
      resources:
         limits:
            cpus: "2.00"
            memory: 500M
         reservations:
            memory: 100M

  archiver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDatabaseConnectionString=mongodb://mongoadmin:mongoadmin@archiver-mongo:27017?maxPoolSize=500
      - HangfireConnectionString=archiver-redis:6379
      - SeqServerUrl=http://seq
    ports:
      - "30002:80"

  archiver-dapr:
    command: ["./daprd",
      "-app-id", "archiver",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    deploy:
      resources:
         limits:
            cpus: "2.00"
            memory: 500M
         reservations:
            memory: 100M

  archiver-mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes:
      - archiver-nosqldata:/data/db
    ports:
      - "27017:27017"

  collector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ImageStorageEndpoint=collector-minio:9000
      - ImageStorageAccessKey=minio
      - ImageStorageSecretKey=minio123
      - HangfireConnectionString=collector-redis:6379
      - SeqServerUrl=http://seq
    ports:
      - "30003:80"

  collector-dapr:
    command: ["./daprd",
      "-app-id", "collector",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    deploy:
      resources:
         limits:
            cpus: "2.00"
            memory: 500M
         reservations:
            memory: 100M

  collector-minio:
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - collector-objectdata:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  #collector-redis:
  #  volumes:
  #    - collector-redisdata:/data

  compressor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ImageStorageEndpoint=compressor-minio:9000
      - ImageStorageAccessKey=minio
      - ImageStorageSecretKey=minio123
      - HangfireConnectionString=compressor-redis:6379
      - SeqServerUrl=http://seq
    ports:
      - "30004:80"

  compressor-dapr:
    command: ["./daprd",
      "-app-id", "compressor",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    deploy:
      resources:
         limits:
            cpus: "2.00"
            memory: 500M
         reservations:
            memory: 100M

  compressor-minio:
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - compressor-objectdata:/data
    ports:
      - "19000:9000"
      - "19001:9001"

  yandestore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DBConnectionString=Host=yandestore-postgres;Database=postgres;Username=root;Password=postgres;
      - HangfireConnectionString=yandestore-redis:6379
      - RetryMigrations=true
      - SeqServerUrl=http://seq
    ports:
      - "30005:80"

  yandestore-dapr:
    command: ["./daprd",
      "-app-id", "yandestore",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    deploy:
      resources:
         limits:
            cpus: "2.00"
            memory: 500M
         reservations:
            memory: 100M

  yandestore-postgres:
    environment:
      POSTGRES_USER: root 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    volumes:
      - yandestore-sqldata:/var/lib/postgresql/data

  yandestore-redis:
    image: redis:7

volumes:
  seq-data:
  archiver-nosqldata:
  collector-objectdata:
  #collector-redisdata:
  compressor-objectdata:
  yandestore-sqldata:
