version: '3.4'

services:
  mongo:
    image: mongo:4

  postgres:
    image: postgres:14

  redis:
    image: redis:7

  redis-easycaching:
    image: redis:7

  redis-hangfire:
    image: redis:7

  rabbitmq:
    image: rabbitmq:management-alpine

  minio:
    image: minio/minio:latest

  zipkin:
    image: openzipkin/zipkin-slim

  dapr-placement:
    image: "daprio/dapr:latest"

  grabber:
    image: ${DOCKER_REGISTRY-}ashlakeservicesgrabber
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Grabber/Dockerfile

  grabber-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:grabber"
    depends_on:
      - grabber

  archiver:
    image: ${DOCKER_REGISTRY-}ashlakeservicesarchiver
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Archiver/Dockerfile
    depends_on:
      - redis-hangfire
      - grabber

  archiver-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:archiver"
    depends_on:
      - archiver

  yande:
    image: ${DOCKER_REGISTRY-}ashlakeservicesyande
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Yande/Dockerfile

  yande-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:yande"
    depends_on:
      - yande
