version: '3.4'

services:
  mongo:
    image: mongo:4

  postgres:
    image: postgres:14

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:management-alpine

  minio:
    image: minio/minio:latest

  zipkin:
    image: openzipkin/zipkin-slim

  grabber:
    image: ${DOCKER_REGISTRY-}ashlakeservicesgrabber
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Grabber/Dockerfile

  grabber-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:grabber"
    depends_on:
      - grabber

  archiver:
    image: ${DOCKER_REGISTRY-}ashlakeservicesarchiver
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Archiver/Dockerfile

  archiver-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:archiver"
    depends_on:
      - archiver