version: '3.4'

services:
  mongo:
    image: mongo:4

  postgres-yandestore:
    image: postgres:14

  redis-easycaching:
    image: redis:7

  redis-hangfire:
    image: redis:7

  redis-state:
    image: redis:7

  rabbitmq:
    image: rabbitmq:management-alpine

  minio:
    image: minio/minio:latest

  seq:
    image: datalust/seq:latest

  zipkin:
    image: openzipkin/zipkin-slim

  healthcheck:
    image: xabarilcoding/healthchecksui:5.0.0
    depends_on:
      - grabber
      - archiver
      - collector
      - yandestore

  grabber:
    image: ${DOCKER_REGISTRY-}ashlakeservicesgrabber
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Grabber/Dockerfile
    depends_on:
      - redis-easycaching

  grabber-dapr:
    image: "daprio/daprd:1.7.2"
    network_mode: "service:grabber"
    depends_on:
      - grabber

  archiver:
    image: ${DOCKER_REGISTRY-}ashlakeservicesarchiver
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Archiver/Dockerfile
    depends_on:
      - redis-hangfire
      - mongo
      - grabber

  archiver-dapr:
    image: "daprio/daprd:1.7.2"
    network_mode: "service:archiver"
    depends_on:
      - archiver

  collector:
    image: ${DOCKER_REGISTRY-}ashlakeservicescollector
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Collector/Dockerfile
    depends_on:
      - minio
      - redis-hangfire
      - grabber
      - archiver

  collector-dapr:
    image: "daprio/daprd:1.7.2"
    network_mode: "service:collector"
    depends_on:
      - collector

  compressor:
    image: ${DOCKER_REGISTRY-}ashlakeservicescompressor
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Compressor/Dockerfile
    depends_on:
      - collector

  compressor-dapr:
    image: "daprio/daprd:1.7.2"
    network_mode: "service:compressor"
    depends_on:
      - compressor

  yandestore:
    image: ${DOCKER_REGISTRY-}ashlakeservicesyandestore
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.YandeStore/Dockerfile
    depends_on:
      - archiver
      - postgres-yandestore

  yandestore-dapr:
    image: "daprio/daprd:1.7.2"
    network_mode: "service:yandestore"
    depends_on:
      - yandestore