version: '3.4'

services:
  mongo:
    image: mongo:4

  postgres:
    image: postgres:14

  redis:
    image: redis:7

  redis-easycaching:
    image: redis:7

  redis-hangfire:
    image: redis:7

  rabbitmq:
    image: rabbitmq:management-alpine

  minio:
    image: minio/minio:latest

  zipkin:
    image: openzipkin/zipkin-slim

  dapr-placement:
    image: "daprio/dapr:latest"

  grabber:
    image: ${DOCKER_REGISTRY-}ashlakeservicesgrabber
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Grabber/Dockerfile
    depends_on:
      - redis-easycaching

  grabber-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:grabber"
    depends_on:
      - grabber

  archiver:
    image: ${DOCKER_REGISTRY-}ashlakeservicesarchiver
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.Archiver/Dockerfile
    depends_on:
      - redis-hangfire
      - mongo
      - grabber

  archiver-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:archiver"
    depends_on:
      - archiver

  yandestore:
    image: ${DOCKER_REGISTRY-}ashlakeservicesyandestore
    build:
      context: .
      dockerfile: src/Services/AshLake.Services.YandeStore/Dockerfile
    depends_on:
      - archiver
      - postgres

  yandestore-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:yandestore"
    depends_on:
      - yandestore
