version: '3.4'

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes:
      - archiver-nosqldata:/data/db
    ports:
      - "27017:27017"

  postgres-yandestore:
    environment:
      POSTGRES_USER: root 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - yandestore-sqldata:/var/lib/postgresql/data

  postgres-hangfire:
    environment:
      POSTGRES_USER: root 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - hangfire-data:/var/lib/postgresql/data

  redis-easycaching:

  redis-state:

  rabbitmq:
    ports:
      - "5672:5672"

  minio:
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - collector-objectdata:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  seq:
    environment:
      - ACCEPT_EULA=Y
      - SEQ_CACHE_SYSTEMRAMTARGET=0.2
    volumes:
      - seq-data:/data
    ports:
      - "5340:80"

  zipkin:
    ports:
      - "9411:9411"

  healthcheck:
    environment:
      - HealthChecksUI__HealthChecks__0__Name=Grabber API
      - HealthChecksUI__HealthChecks__0__Uri=http://grabber/hc
      - HealthChecksUI__HealthChecks__1__Name=Archiver API
      - HealthChecksUI__HealthChecks__1__Uri=http://archiver/hc
      - HealthChecksUI__HealthChecks__2__Name=Collector API
      - HealthChecksUI__HealthChecks__2__Uri=http://collector/hc
      - HealthChecksUI__HealthChecks__3__Name=Compressor API
      - HealthChecksUI__HealthChecks__3__Uri=http://compressor/hc
      - HealthChecksUI__HealthChecks__4__Name=YandeStore API
      - HealthChecksUI__HealthChecks__4__Uri=http://yandestore/hc
    ports:
      - "5107:80"

  grabber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - YandeUrl=https://yande.re/
      - DanbooruUrl=https://danbooru.donmai.us/
      - KonachanUrl=https://konachan.com/
      - EasycachingRedisHost=redis-easycaching
      - SeqServerUrl=http://seq
    ports:
      - "80"
      - "7777"

  grabber-dapr:
    command: ["./daprd",
      "-app-id", "grabber",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-max-request-size","128",
      "-enable-profiling","true",
      "-log-level", "debug",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  archiver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDatabaseConnectionString=mongodb://mongoadmin:mongoadmin@mongo:27017?maxPoolSize=500
      - HangfireConnectionString=Host=postgres-hangfire;Database=postgres;Username=root;Password=postgres;MaxPoolSize=500;
      - SeqServerUrl=http://seq
    ports:
      - "80"

  archiver-dapr:
    command: ["./daprd",
      "-app-id", "archiver",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-max-request-size","128",
      "-dapr-http-read-buffer-size","64",
      "-log-level", "debug",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
     
  collector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ImageStorageEndpoint=minio:9000
      - ImageStorageAccessKey=minio
      - ImageStorageSecretKey=minio123
      - HangfireConnectionString=Host=postgres-hangfire;Database=postgres;Username=root;Password=postgres;MaxPoolSize=500;
      - SeqServerUrl=http://seq
    ports:
      - "80"

  collector-dapr:
    command: ["./daprd",
      "-app-id", "collector",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-max-request-size","128",
      "-log-level", "debug",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  compressor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ImageStorageEndpoint=minio:9000
      - ImageStorageAccessKey=minio
      - ImageStorageSecretKey=minio123
      - HangfireConnectionString=Host=postgres-hangfire;Database=postgres;Username=root;Password=postgres;MaxPoolSize=500;
      - SeqServerUrl=http://seq
    ports:
      - "80"

  compressor-dapr:
    command: ["./daprd",
      "-app-id", "compressor",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-max-request-size","128",
      "-log-level", "debug",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  yandestore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DBConnectionString=Host=postgres-yandestore;Database=postgres;Username=root;Password=postgres;MaxPoolSize=500;
      - HangfireConnectionString=Host=postgres-hangfire;Database=postgres;Username=root;Password=postgres;MaxPoolSize=500;
      - RetryMigrations=true
      - SeqServerUrl=http://seq
    ports:
      - "80"

  yandestore-dapr:
    command: ["./daprd",
      "-app-id", "yandestore",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-read-buffer-size","64",
      "-log-level", "debug",
      "-config", "/configuration/ashlake-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

volumes:
  seq-data:
  hangfire-data:
  archiver-nosqldata:
    external: false
  collector-objectdata:
    external: false
  yandestore-sqldata:
    external: false
