apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: default
spec:
  tracing:
    samplingRate: "0.0001"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"